#!/usr/bin/env bash

set -euo pipefail

command="runhaskell -XOverloadedStrings $*"

dir=$(dirname "$0")

if [[ -n ${IN_NIX_SHELL:-} ]]; then
  # Already in nix-shell.
  $command
else
  # Run the command inside a nix-shell.
  exec nix-shell --command "${command}" "${dir}/shell.nix"
fi
